import assert from "node:assert/strict";
import { test } from "node:test";
import { existsSync } from "node:fs";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import * as os from "node:os";
import { fileURLToPath } from "node:url";
import { runSettingsWorker } from "./omp-settings-worker.ts";
import type { ConfigRecord, SettingsSnapshot } from "./omp-settings-core.ts";

const packageRoot = process.env.OMP_SETTINGS_TEST_PACKAGE_ROOT ?? path.join(os.homedir(), ".bun", "install", "global", "node_modules", "@oh-my-pi", "pi-coding-agent");
const bunPath = process.env.OMP_SETTINGS_TEST_BUN ?? path.join(os.homedir(), ".bun", "bin", process.platform === "win32" ? "bun.exe" : "bun");
const helperPath = fileURLToPath(new URL("../omp/settings-worker.ts", import.meta.url));
interface Receipt { snapshot: SettingsSnapshot; files: { global: ConfigRecord; project: ConfigRecord } }
test("installed OMP readonly discovery, native scopes, atomic config merge and definition creation", { skip: !existsSync(packageRoot) || !existsSync(bunPath), timeout: 120_000 }, async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "omp-settings-contract-"));
  const nativeRoot = await fs.mkdtemp(path.join(os.homedir(), "omp-desk-settings-test-"));
  const cwd = path.join(root, "project"); const agentDir = path.join(nativeRoot, "agent");
  const globalFile = path.join(agentDir, "config.yaml"); const projectFile = path.join(cwd, ".omp", "config.yml");
  await fs.mkdir(path.join(agentDir, "agents"), { recursive: true }); await fs.mkdir(path.dirname(projectFile), { recursive: true });
  await fs.writeFile(globalFile, "modelRoleStorage: project\nmodelRoles:\n  default: settings-fixture/fixture-model\n  smol: settings-fixture/fixture-model\nunknown:\n  keep: original\n");
  await fs.writeFile(projectFile, "modelRoles:\n  slow: settings-fixture/fixture-model\nprojectUnknown: retain\n");
  await fs.writeFile(path.join(agentDir, "models.yml"), "providers:\n  settings-fixture:\n    api: openai-completions\n    baseUrl: https://example.invalid/v1\n    apiKey: fixture-never-used-for-network\n    models:\n      - id: fixture-model\n        name: Settings Fixture\n        reasoning: true\n        contextWindow: 8192\n        maxTokens: 1024\n");
  await fs.writeFile(path.join(agentDir, "agents", "settings-helper.md"), "---\nname: settings-helper\ndescription: Use this agent when testing settings discovery\n---\nInspect the fixture.\n");
  const call = (request: ConfigRecord) => runSettingsWorker({ packageRoot, bunPath, helperPath, cwd, profile: "default", request, env: { PI_CONFIG_DIR: path.basename(nativeRoot), PI_CODING_AGENT_DIR: "", PI_CONFIG_FILES: "", OMP_AUTH_BROKER_URL: "", OMP_AUTH_BROKER_TOKEN: "" } });
  try {
    const before = await fs.readFile(globalFile, "utf8");
    let receipt = await call({ action: "read" }) as Receipt;
    assert.equal(receipt.snapshot.globalFile, globalFile);
    assert.equal(receipt.snapshot.effective.modelRoleStorage, "project");
    assert.ok(receipt.snapshot.roles.some(role => role.id === "smol" && role.selector === "settings-fixture/fixture-model"));
    assert.ok(receipt.snapshot.agents.some(agent => agent.name === "settings-helper"));
    assert.equal(receipt.snapshot.agentDirectories.global, path.join(agentDir, "agents"));
    assert.equal(receipt.snapshot.agentDirectories.project, path.join(cwd, ".omp", "agents"));
    assert.equal(receipt.snapshot.models.find(model => model.provider === "settings-fixture")?.reasoning, true);
    assert.equal(await fs.readFile(globalFile, "utf8"), before);
    assert.equal(existsSync(path.join(agentDir, "agent.db")), false, "opening does not create credentials/usage storage");
    assert.equal(existsSync(path.join(agentDir, "models.db")), false, "opening does not initialize the native catalogue cache");
    await fs.writeFile(globalFile, `# kept comment\n${before}`);
    receipt = await call({ action: "read" }) as Receipt;
    assert.deepEqual(await call({ action: "write", scope: "global", baseline: receipt.files.global, edits: [{ path: ["task", "agentAdvisor", "settings-helper"] }] }), { saved: true, changed: false });
    assert.equal(await fs.readFile(globalFile, "utf8"), `# kept comment\n${before}`, "a no-op clear never rewrites the file or strips its comments");
    await fs.writeFile(globalFile, before);
    receipt = await call({ action: "read" }) as Receipt;
    await fs.appendFile(globalFile, "externalUnknown: retained\n");
    await call({ action: "write", scope: "global", baseline: receipt.files.global, edits: [{ path: ["modelRoles", "smol"], value: "settings-fixture/fixture-model:high" }, { path: ["task", "agentModelOverrides", "settings-helper"], value: "settings-fixture/fixture-model" }, { path: ["task", "agentPrewalk", "settings-helper"], value: "off" }] });
    receipt = await call({ action: "read" }) as Receipt;
    assert.equal(receipt.snapshot.roles.find(role => role.id === "smol")?.selector, "settings-fixture/fixture-model:high");
    assert.equal(receipt.snapshot.agents.find(agent => agent.name === "settings-helper")?.overrideModel, "settings-fixture/fixture-model");
    const changed = await fs.readFile(globalFile, "utf8");
    assert.match(changed, /externalUnknown: retained/); assert.match(changed, /keep: original/);
    await call({ action: "write", scope: "project", baseline: receipt.files.project, edits: [{ path: ["modelRoles", "slow"], value: null }] });
    assert.match(await fs.readFile(projectFile, "utf8"), /slow: null/); assert.match(await fs.readFile(projectFile, "utf8"), /projectUnknown: retain/);
    await assert.rejects(call({ action: "write", scope: "project", baseline: receipt.files.project, edits: [{ path: ["task", "disabledAgents"], value: ["settings-helper"] }] }));
    const concurrent = await call({ action: "read" }) as Receipt;
    await fs.appendFile(globalFile, "\ncycleOrder:\n  - slow\n");
    await assert.rejects(call({ action: "write", scope: "global", baseline: concurrent.files.global, edits: [{ path: ["cycleOrder"], value: ["default"] }] }));
    assert.match(await fs.readFile(globalFile, "utf8"), /- slow/);
    const latest = await call({ action: "read" }) as Receipt;
    await assert.rejects(call({ action: "write", scope: "global", baseline: latest.files.global, edits: [{ path: ["task", "agentPrewalk", "settings-helper"], value: "model-that-does-not-exist" }] }));
    const savePreset = await call({ action: "preset-plan", operation: "save", preset: "fixture" }) as ConfigRecord;
    await call({ action: "write", ...savePreset, baseline: latest.files.global });
    const withPreset = await call({ action: "read" }) as Receipt;
    assert.ok(withPreset.snapshot.presetNames.includes("fixture"));
    const preset = withPreset.snapshot.global.modelPresets as ConfigRecord;
    assert.equal(((preset.fixture as ConfigRecord).modelRoles as ConfigRecord).smol, "settings-fixture/fixture-model:high");
    const applyPreset = await call({ action: "preset-plan", operation: "switch", preset: "fixture" }) as ConfigRecord;
    assert.equal(applyPreset.scope, "project");
    await call({ action: "write", ...applyPreset, baseline: withPreset.files.project });
    const applied = await call({ action: "read" }) as Receipt;
    assert.equal((applied.snapshot.project.modelRoles as ConfigRecord).default, "settings-fixture/fixture-model");
    assert.equal(applied.snapshot.project.projectUnknown, undefined, "unowned values are withheld from browser metadata");
    assert.match(await fs.readFile(projectFile, "utf8"), /projectUnknown: retain/);
    await call({ action: "write", scope: "global", baseline: applied.files.global, edits: [{ path: ["task", "disabledAgents"], value: ["settings-helper"] }] });
    const disabled = await call({ action: "read" }) as Receipt;
    assert.equal(disabled.snapshot.agents.find(agent => agent.name === "settings-helper")?.disabled, true);
    const spec = { identifier: "created-helper", whenToUse: "Use this agent when checking a created definition", systemPrompt: "Read the fixture only." };
    await call({ action: "create", scope: "global", spec });
    assert.match(await fs.readFile(path.join(agentDir, "agents", "created-helper.md"), "utf8"), /Read the fixture only/);
    await assert.rejects(call({ action: "create", scope: "global", spec }));
    await fs.writeFile(globalFile, "bad: [\nsecretCredential: should-not-leak\n");
    await assert.rejects(call({ action: "read" }), error => error instanceof Error && !error.message.includes("should-not-leak"));
    assert.match(await fs.readFile(globalFile, "utf8"), /should-not-leak/);
    await fs.rm(globalFile);
    const missing = await call({ action: "read" }) as Receipt;
    assert.equal(missing.files.global.exists, false);
    await call({ action: "write", scope: "global", baseline: missing.files.global, edits: [{ path: ["modelRoles", "smol"], value: "settings-fixture/fixture-model" }] });
    assert.match(await fs.readFile(path.join(agentDir, "config.yml"), "utf8"), /smol: settings-fixture\/fixture-model/);
  } finally { await fs.rm(root, { recursive: true, force: true }); await fs.rm(nativeRoot, { recursive: true, force: true }); }
});
